export const enum NATIVE_APP_MESSAGE_TYPES {
    DIGILOCKER_SUCCESS = 'DIGILOCKER_SUCCESS',
    FACE_KYC_SUCCESS = 'FACE_KYC_SUCCESS',
    BANK_STATEMENT_SUCCESS = 'BANK_STATEMENT_SUCCESS',
    ESIGN_SUCCESS = 'ESIGN_SUCCESS',
    ENACH_SUCCESS = 'ENACH_SUCCESS',
    FAQ_SUCCESS = 'FAQ_SUCCESS',
    SUPPORT_SUCCESS = 'SUPPORT_SUCCESS',
}
  